blog/urls.py
from django.urls import path
from . import views
from .views import (
    PostListView,
    UserPostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
)
app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-post'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name = 'post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='about')

]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
#app_name = 'main_app'
urlpatterns = [
    path('', include('blog.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name= 'logout'),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),

    path('password-reset/done/',
            auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
            name='password_reset_done'
        ),

    path('password-reset-confirm/<uidb64>/<token>/',
            auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
            name='password_reset_confirm'
        ),
    path('password-reset-complete/',
            auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
            name='password_reset_complete'
        ),

    path('admin/', admin.site.urls),
    #path('blog/', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 100)
    content = models.TextField()
    date_posted = models.DateTimeField(default = timezone.now)
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs = {'pk':self.id})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    image = models.ImageField(default = 'default.jpg', upload_to = 'profile_pics')

    def __str__(self):
        #return "%s Profile" %self.user.username
        return "{} Profile".format(self.user.username)

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)

    #     img = Image.open(self.image.path)

    #     if img.height > 300 or img.width > 300:
    #         outputsize = (300, 300)
    #         img.thumbnail(outputsize)
    #         img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean(self):
        cd = self.cleaned_data

        email = cd.get("email")
        uname = cd.get("username")
        temp = User.objects.all()
        for usr in temp:
            if usr.username == uname:
                raise forms.ValidationError("UserName already in use")

        for usr in temp:
            if usr.email == email:
                raise forms.ValidationError("Email already in use")
        return cd


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.contrib.auth.models import User
from django.shortcuts import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# def home(request):
#     context = {
#         'posts':Post.objects.all()
#     }
#     return render(request, 'blog/home.html',context)

class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/home.html'
    paginate_by = 3
    ordering = ['-date_posted']


class UserPostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/user_post.html'
    paginate_by = 3
    def get_queryset(self):
        user = get_object_or_404(User, username = self.kwargs.get('username'))
        print(user.username)
        return Post.objects.filter(author=user).order_by('-date_posted')




class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = "/"
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False




def about(request):
    return render(request, 'blog/about.html',{'title':'About'})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
# Create your views here.

def register(request):
    # temp = User.objects.all()
    # for usr in temp:
    #     print("Username {}, Email {}".format(usr.username, usr.email))
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)

        if form.is_valid(): # clean method is called when i am calling form.is_valid where i check whether email already exists or not
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, "Account created for %s!"%username)
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form':form})

@login_required
def profile(request):
    #print("USERRRR{}".format(type(request.user)))
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,instance = request.user)
        p_form = ProfileUpdateForm(request.POST ,
                                    request.FILES,
                                    instance = request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, "details updated successfully!")
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance = request.user)
        p_form = ProfileUpdateForm(instance = request.user.profile)

    context = {
        'u_form' : u_form,
        'p_form' : p_form
    }
    return render(request, 'users/profile.html', context)

blog/templates/blog/about.html
{%extends 'blog/base.html' %}
{%block content%}
    <h1>Blog About</h1>
{%endblock content%}

blog/templates/blog/base.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet"  type=" text/css" href="{%static 'blog/main.css'%}">
    {% if title %}
        <title>Django-Blog {{title}}</title>
    {% else %}
        <title>Django-Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{%url 'blog:home'%}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog:home'%}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blog:about'%}">About</a>

            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'blog:post-create'%}">New Post</a>
              {% if user.is_authenticated %}

              <a class="nav-item nav-link" href="{% url 'logout'%}">Logout</a>
              <a class="nav-item nav-link" href="{% url 'profile'%}">Profile</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'register'%}">Register</a>
              <a class="nav-item nav-link" href="{% url 'login'%}">Login</a>
              {% endif %}


            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
          {%if messages%}
          {%for message in messages%}
            <div class="alert alert-{{message.tags}}">
              {{message}}
            </div>

          {%endfor%}
          {%endif%}
          {% block content %}{% endblock %}

        </div>
        <!-- <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div> -->
      </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% block content%}
    {% for post in posts %}
        <article class="media content-section">
          <img class = "rounded-circle article-img" src="{{post.author.profile.image.url}}">
          <div class="media-body">
            <div class="article-metadata">
              <!-- made changes here!--><a class="mr-2" href="{% url 'blog:user-post' post.author%}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class = "btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class = "btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
        {% endif%}

        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
            {% elif num < page_obj.number|add:'3' and num > page_obj.number|add:'-3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
            {%endif%}
        {% endfor%}

        {% if page_obj.has_next %}
            <a class = "btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
            <a class = "btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
        {% endif%}

    {% endif%}
{% endblock content%}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Do you want to delete the post {{object.title}} ?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:home'%}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'blog:user-post' object.author %}">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        <!-- <h7>{{user.username}}</h7> -->
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content }}</p>
    </div>
  </article>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/user_post.html
{% extends 'blog/base.html' %}
{% block content%}
    <h2 class="mb-3">Posts by the user {{view.kwargs.username}} </h2>
    <h2 class="bm-3"> Total {{page_obj.paginator.count}} Post</h2>
    {% for post in posts %}
        <article class="media content-section">
          <img class = "rounded-circle article-img" src="{{post.author.profile.image.url}}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'blog:user-post' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class = "btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class = "btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
        {% endif%}

        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
            {% elif num < page_obj.number|add:'3' and num > page_obj.number|add:'-3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
            {%endif%}
        {% endfor%}

        {% if page_obj.has_next %}
            <a class = "btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
            <a class = "btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
        {% endif%}

    {% endif%}
{% endblock content%}

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
                <small class="text-muted ml-2">
                    <a href="{% url 'password_reset' %}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Password Reset</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Password Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "blog/home.html"%}
{% block content %}
    <div class="alert alert-info">
        Password Set Successfully!!
    </div>
    <a href="{%url 'login' %}">Sign In </a>
{% endblock content%}

users/templates/users/password_reset_confirm.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Password Reset</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "blog/home.html"%}
{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock content%}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
   <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login'%}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}